#!/bin/bash

# Welcome message
clear
echo
echo "              __   ___ .  __      __        __   __"
echo "  /\\  |    | /  \` |__  ' /__\`    |__)  /\\  /__\` /__\` "
echo " /~~\\ |___ | \\__, |___   .__/    |    /~~\\ .__/ .__/ "
echo

# Create working directory and file
alice_home=~/.alices_password
if [ ! -d $alice_home ]
then
	mkdir $alice_home
fi

# Create encrypted file
if [ ! -e $alice_home/passwords.gpg ]
then
	touch $alice_home/passwords.gpg
fi

# Update
echo After updates, press :wq to exit
echo 'press <ENTER> to start editing.'
echo
read toto
	
# Decrypt file
declare OUTPUT="$(gpg -o $alice_home/passwords -d $alice_home/passwords.gpg 2>&1)"
if [[ $OUTPUT != *"decryption failed"* ]]; then
	rm $alice_home/passwords.gpg
		
	# Encrypt
	vim $alice_home/passwords
	gpg --symmetric --cipher-algo AES256 $alice_home/passwords
	rm $alice_home/passwords	
fi
exit
